#DATA
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huaweidb
    username: app_user
    password: app_password
  data:
    web:
      pageable:
        default-page-size: 50 # Default page size.

#ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: '*'

#DOCUMENTATION
springdoc:
  api-docs:
    enabled: true
    path: /api/v1/api-docs
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html